version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: true
      CHOKIDAR_USEPOLLING: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - nextjs-network
    stdin_open: true
    tty: true

networks:
  nextjs-network:
    driver: bridge
